import { PrismaClient } from "@prisma/client";
import { PrismaNeon } from "@prisma/adapter-neon";
import "dotenv/config";
import * as data from "./seed-data";

/**
 * Seed the Chowly database.
 *
 * Requirement 1 asks for the menu to be loaded into the database by me, and
 * requirement 3 for a staff list loaded by me. Both are here, along with a
 * history of orders so that the waiter's queue and the ratings and complaints
 * have something real in them the moment the deployed link is opened.
 *
 * The records come from './seed-data.ts', which is generated by
 * docs/generate-seed-data.py from 'Chowly - Seed Data.xlsx'. Every row passed
 * the consistency checks listed on that workbook's Summary sheet — subtotals,
 * order totals, payment amounts and foreign keys are all verified before the
 * data ever reaches this file.
 *
 * Identifiers are the ones used in the Assignment 1 model (R1, S201, CAT01,
 * MN01, IT001, ORD001) rather than generated ids, so the rows in the running
 * database can be read side by side with the model that was submitted. Records
 * the application creates later get generated ids as normal.
 *
 * Reference data — restaurants, staff, categories, menus, items — is upserted,
 * so re-running only updates it in place.
 *
 * Orders are different. They are REBUILT rather than upserted: the seeded ones
 * are deleted first and written again. Upserting them was not harmless, however
 * much the comment here used to claim it was. Regenerating the dataset changes
 * which items belong to which order, and an upsert wrote the new lines while
 * leaving the old ones behind — so an order ended up carrying both, and its
 * line items no longer added up to its total. Deleting first is what makes the
 * seeded data match the spreadsheet exactly instead of accumulating.
 *
 * Only orders whose id comes from the seed (ORD001…) are touched. Orders placed
 * through the application have generated ids and are left alone.
 */

const connectionString = process.env.DIRECT_URL ?? process.env.DATABASE_URL;

if (!connectionString) {
  throw new Error(
    "DIRECT_URL (or DATABASE_URL) must be set to seed. Copy .env.example to .env first."
  );
}

const prisma = new PrismaClient({
  adapter: new PrismaNeon({ connectionString }),
});

/** Upsert a list of records keyed by `id`, reporting progress. */
async function seed<T extends { id: string }>(
  label: string,
  rows: T[],
  upsert: (row: T) => Promise<unknown>
) {
  for (const row of rows) await upsert(row);
  console.log(`  ${label.padEnd(18)} ${String(rows.length).padStart(4)}`);
}

async function main() {
  console.log("Seeding Chowly...\n");

  // Order matters: a row cannot be written before the rows it points at.

  await seed("restaurants", data.restaurants, (r) =>
    prisma.restaurant.upsert({ where: { id: r.id }, update: r, create: r })
  );

  await seed("categories", data.categories, (c) =>
    prisma.category.upsert({ where: { id: c.id }, update: c, create: c })
  );

  await seed("customers", data.customers, (c) =>
    prisma.customer.upsert({ where: { id: c.id }, update: c, create: c })
  );

  await seed("staff", data.staff, (s) =>
    prisma.staff.upsert({ where: { id: s.id }, update: s, create: s })
  );

  await seed("menus", data.menus, (m) =>
    prisma.menu.upsert({ where: { id: m.id }, update: m, create: m })
  );

  await seed("menu items", data.menuItems, (i) =>
    prisma.menuItem.upsert({ where: { id: i.id }, update: i, create: i })
  );

  // Clear out the previous version of the seeded orders before writing this
  // one. Items, preparation, complaints, ratings and payments all cascade from
  // the order, so removing the orders removes everything hanging off them and
  // nothing is left over from a differently-shaped earlier dataset.
  const seededOrderIds = data.orders.map((o) => o.id);
  const removed = await prisma.customerOrder.deleteMany({
    where: { id: { in: seededOrderIds } },
  });
  if (removed.count > 0) {
    console.log(`  ${"(rebuilding)".padEnd(18)} ${String(removed.count).padStart(4)} old orders cleared`);
  }

  await seed("orders", data.orders, (o) => prisma.customerOrder.create({ data: o }));

  // OrderItem has a composite primary key rather than a single id.
  await prisma.orderItem.createMany({ data: data.orderItems });
  console.log(`  ${"order items".padEnd(18)} ${String(data.orderItems.length).padStart(4)}`);

  await seed("preparations", data.preparations, (p) =>
    prisma.orderPreparation.upsert({ where: { id: p.id }, update: p, create: p })
  );

  await seed("complaints", data.complaints, (c) =>
    prisma.complaint.upsert({ where: { id: c.id }, update: c, create: c })
  );

  await seed("ratings", data.ratings, (r) =>
    prisma.rating.upsert({ where: { id: r.id }, update: r, create: r })
  );

  await seed("payments", data.payments, (p) =>
    prisma.payment.upsert({ where: { id: p.id }, update: p, create: p })
  );

  const total =
    data.restaurants.length + data.categories.length + data.customers.length +
    data.staff.length + data.menus.length + data.menuItems.length +
    data.orders.length + data.orderItems.length + data.preparations.length +
    data.complaints.length + data.ratings.length + data.payments.length;

  console.log(`\n  ${"TOTAL".padEnd(18)} ${String(total).padStart(4)} records\n`);
  console.log("Done.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
