import { PrismaClient } from "@prisma/client";
import { PrismaNeon } from "@prisma/adapter-neon";
import "dotenv/config";
import * as data from "./seed-data";

/**
 * Seed the Chowly database.
 *
 * Requirement 1 asks for the menu to be loaded into the database by me, and
 * requirement 3 for a staff list loaded by me. Both are here, along with a
 * history of orders so that the waiter's queue and the ratings and complaints
 * have something real in them the moment the deployed link is opened.
 *
 * The records come from './seed-data.ts', which is generated by
 * docs/generate-seed-data.py from 'Chowly - Seed Data.xlsx'. Every row passed
 * the consistency checks listed on that workbook's Summary sheet — subtotals,
 * order totals, payment amounts and foreign keys are all verified before the
 * data ever reaches this file.
 *
 * Identifiers are the ones used in the Assignment 1 model (R1, S201, CAT01,
 * MN01, IT001, ORD001) rather than generated ids, so the rows in the running
 * database can be read side by side with the model that was submitted. Records
 * the application creates later get generated ids as normal.
 *
 * Everything is upserted, so running this twice is harmless.
 */

const connectionString = process.env.DIRECT_URL ?? process.env.DATABASE_URL;

if (!connectionString) {
  throw new Error(
    "DIRECT_URL (or DATABASE_URL) must be set to seed. Copy .env.example to .env first."
  );
}

const prisma = new PrismaClient({
  adapter: new PrismaNeon({ connectionString }),
});

/** Upsert a list of records keyed by `id`, reporting progress. */
async function seed<T extends { id: string }>(
  label: string,
  rows: T[],
  upsert: (row: T) => Promise<unknown>
) {
  for (const row of rows) await upsert(row);
  console.log(`  ${label.padEnd(18)} ${String(rows.length).padStart(4)}`);
}

async function main() {
  console.log("Seeding Chowly...\n");

  // Order matters: a row cannot be written before the rows it points at.

  await seed("restaurants", data.restaurants, (r) =>
    prisma.restaurant.upsert({ where: { id: r.id }, update: r, create: r })
  );

  await seed("categories", data.categories, (c) =>
    prisma.category.upsert({ where: { id: c.id }, update: c, create: c })
  );

  await seed("customers", data.customers, (c) =>
    prisma.customer.upsert({ where: { id: c.id }, update: c, create: c })
  );

  await seed("staff", data.staff, (s) =>
    prisma.staff.upsert({ where: { id: s.id }, update: s, create: s })
  );

  await seed("menus", data.menus, (m) =>
    prisma.menu.upsert({ where: { id: m.id }, update: m, create: m })
  );

  await seed("menu items", data.menuItems, (i) =>
    prisma.menuItem.upsert({ where: { id: i.id }, update: i, create: i })
  );

  await seed("orders", data.orders, (o) =>
    prisma.customerOrder.upsert({ where: { id: o.id }, update: o, create: o })
  );

  // OrderItem has a composite primary key rather than a single id.
  for (const li of data.orderItems) {
    await prisma.orderItem.upsert({
      where: { orderId_itemId: { orderId: li.orderId, itemId: li.itemId } },
      update: li,
      create: li,
    });
  }
  console.log(`  ${"order items".padEnd(18)} ${String(data.orderItems.length).padStart(4)}`);

  await seed("preparations", data.preparations, (p) =>
    prisma.orderPreparation.upsert({ where: { id: p.id }, update: p, create: p })
  );

  await seed("complaints", data.complaints, (c) =>
    prisma.complaint.upsert({ where: { id: c.id }, update: c, create: c })
  );

  await seed("ratings", data.ratings, (r) =>
    prisma.rating.upsert({ where: { id: r.id }, update: r, create: r })
  );

  await seed("payments", data.payments, (p) =>
    prisma.payment.upsert({ where: { id: p.id }, update: p, create: p })
  );

  const total =
    data.restaurants.length + data.categories.length + data.customers.length +
    data.staff.length + data.menus.length + data.menuItems.length +
    data.orders.length + data.orderItems.length + data.preparations.length +
    data.complaints.length + data.ratings.length + data.payments.length;

  console.log(`\n  ${"TOTAL".padEnd(18)} ${String(total).padStart(4)} records\n`);
  console.log("Done.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
